import { program } from 'commander'
import { Options } from '../types'

export function getOptions(): Options {
  program
    .name('flaky-test-detector')
    .description('Rerun tests suite to detect flaky tests')
    .version('1.0.2')

  program
    .option(
      '--run-tests <string>',
      'Command use to run the tests (ex: "npm test")'
    )
    .option(
      '--test-output-file <path>',
      'Path to the report file generated by the tests'
    )
    .option(
      '--test-output-format <junit|cucumberJson>',
      'Test output format of the file passed via --test-output-file argument'
    )
    .option(
      '--exit-code <number>',
      'Exit code used when flaky tests are found (default: 1)',
      '1'
    )
    .option('--repeat <number>', 'Number of executions', '10')

  program.parse()
  return program.opts()
}
