import { program } from "commander";
import { Options } from "../types";

export function getOptions(): Options {
  program
    .name("flaky-test-detector")
    .description("Rerun tests suite to detect flaky tests")
    .version("0.0.1");

  program
    .option(
      "--run-tests <string>",
      'Command use to run the tests (ex: "npm test")'
    )
    .option(
      "--test-output-file <path>",
      "Path to the report file generated by the tests"
    )
    .option("--repeat <number>", "Number of executions", "10");

  program.parse();
  return program.opts();
}
